### ISSUE TITLE
Building with stack fails with "Executable named groupadd not found on path" error

### ISSUE THREAD

**Issue by soupi** [utdemir/ghc-musl#12]
Hi! Thank you for making this.

I've been trying to build my project [hablog](https://github.com/soupi/hablog) using the stack method as described in the readme:

> Add ghc-options: -static -optl-static -optl-pthread -fPIC flags to the executable section of your cabal file and these lines to your stack.yaml, and use stack as usual on the host machine:
>
> docker:
>  enable: true
>  image: utdemir/ghc-musl:v15-ghc884

But after running `stack build` I've got the following error:

```
Executable named groupadd not found on path: ["/opt/host/bin","/home/soupi/hablog/.stack-work/docker/_home/.local/bin","/usr/local/.ghcup/bin","/usr/local/sbin","/usr/local/bin","/usr/sbin","/usr/bin","/sbin","/bin"]
```

I'm using stack v2.3.3 and lts-16.15.

Any idea what the issue might be?

Thanks!

**Comment by utdemir** [comment]
Hey, thanks for the report.

That is a bug on our side; turns out we also have to install `shadow` package to get the `groupadd` util `stack` uses. I just published `ghc-musl:v16` which shouldn't have this issue.

I also added a test case for the `stack` use case, so hopefully this won't happen again this easily.

Let me know if it is now working :)

**Comment by soupi** [comment]
That works great! Thank you for the quick reply.
